### ISSUE TITLE
Poor results in the LSTM model (used the weights trained in repo + trained myself)

### ISSUE THREAD

**Issue by franciscovargas** [anandaswarup/phrase_break_prediction_IS16#3]
I can see that in the LSTM experiment a very high accuracy in testing and training are reported

Mean F1 score over test sentences : 0.918860

However. The model simply just predicts NB (class 1) for everything.  Is this mentioned in the paper ??

**Comment by imucsliurui** [comment]
when i run the RNN or LSTM, some messages shows  like this: need to set input_shape in TimeDistributeDense 's. first layer.      So ,what you do in this?  Thank you very much!
Best Regards!
